### ISSUE TITLE
面试常见问题

### ISSUE THREAD

**Issue by ihtml5** [ihtml5/blog#58]
1. 如何绕z轴旋转
```css
  .a {
   -webkit-transform: rotateZ(90deg);
   -webkit-transform: rotate3D(90deg);
}
```
2. 四周都是阴影
```css
   .a {
     -webkit-box-shadow: 0 0 10px #000;
      -ms-box-shadow: 0 0 10px #000;
      -moz-box-shadow: 0 0 10px #000;
      -o-box-shadow: 0 0 10px #000;
      box-shadow: 0 0 10px #000;
   }
```
3. [变量提升](http://www.cnblogs.com/kawask/p/6225317.html)
4. 如何获取一个参数的形参
  /\(\s*([\s\S]*?)\s*\)/.exec(fn)[1].split(/\s*,\s*/)
5. [面向对象编程](http://javascript.ruanyifeng.com/oop/basic.html)
6. 父容器和子容器宽高都不确定，如何让子元素水平垂直居中父元素
  http://blog.csdn.net/jiangbo_phd/article/details/49046143
7. 上下文堆栈
https://segmentfault.com/a/1190000009041008
8. require.js如何解决循环依赖
http://www.cnblogs.com/cheerfulCoder/p/4339742.html
9. [别人总结的面试题](https://github.com/hawx1993/Front-end-Interview-questions/blob/master/README.md)
10. [offsetParent](http://www.cnblogs.com/xiaohuochai/p/5828369.html)
11. [Cookie、sessionStorage、localStorage的区别](http://blog.csdn.net/sugarf/article/details/54176447)
12.  JSONP原理
13. [不再以讹传讹，GET和POST的真正区别](http://www.nowamagic.net/librarys/veda/detail/1919)
14. 一个页面从输入 URL 到页面加载完的过程中都发生了什么事情？越详细越好(考察知识广度)
输入地址-》浏览器查找域名的IP地址（DNS查找）-》浏览器向web服务器发送请求-》服务器永久重定向回应-》浏览器跟踪重定向地址-》服务器处理请求-》服务器返回http响应-》浏览器显示html-》浏览器发送请求获取在html中嵌套的资源-》浏览器发送异步请求
15. [ajax的优缺点](http://www.cnblogs.com/SanMaoSpace/archive/2013/06/15/3137180.html)
